compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  ioanatu:
    npmAuthToken: '${NPM_AUTH_TOKEN:-}'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.16.0.cjs
