name: Build storybook and upload artifact to S3 bucket

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Build and deploy storybook
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install packages
        run: yarn install --immutable

      - name: Build storybook
        run: yarn story:build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload artifact to S3 bucket
        run: aws s3 sync ./storybook-static/ ${{ secrets.AWS_S3_BUCKET_URI }} --cache-control no-cache --delete
